import React from "react";
import type { Metadata } from "next";
import { Container } from "@/components/Container";
import { FAQ } from "@/components/FAQ";
import FooterV2 from "@/components/Footer/FooterV2";
import CustomContainer from "@/components/Container/CustomContainer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ContactLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <React.Fragment>
      <CustomContainer className="pt-20">
        <div>{children}</div>
        <FAQ />
      </CustomContainer>
        <FooterV2 />
    </React.Fragment>
    
  );
}
