import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { End2EndWrapper } from "@/components/End2EndWrapper";
import { Container } from "@/components/Container";
import { Footer } from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ProjectsLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Container className="pt-20">
      <div>{children}</div>
      <Footer />
    </Container>
  );
}
