import type { Metadata } from "next";
import { Container } from "@/components/Container";
import { End2EndWrapper } from "@/components/End2EndWrapper";
import { Header } from "@/components/Header";
import FooterV2 from "@/components/Footer/FooterV2";
import CustomContainer from "@/components/Container/CustomContainer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ProjectsLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="bg-[#F8F7F3]">
      <End2EndWrapper>
        <Header lightBackground={true}/>
      </End2EndWrapper>
      <CustomContainer>
        {children}
      </CustomContainer>
      <FooterV2 />
    </div>
  );
}
