import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { End2EndWrapper } from "@/components/End2EndWrapper";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <End2EndWrapper>
            <Header />
          </End2EndWrapper>
          {children}
          <End2EndWrapper>
            <Footer />
          </End2EndWrapper>
        </main>
      </body>
    </html>
  );
}
