import type { Metadata } from "next";
import "./globals.css";
import { End2EndWrapper } from "@/components/End2EndWrapper";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { playfair } from "@/fonts/playfair";
import { helvetica } from "@/fonts/helvetica";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={helvetica.className}>
        <main>
          <End2EndWrapper>
            <Header />
          </End2EndWrapper>
          {children}
        </main>
      </body>
    </html>
  );
}
